<?php

namespace BW\AdminBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function loadByCategoryId($id){
        $queryBuilder = $this
            ->createQueryBuilder('p')
            ->leftJoin('p.categories', 'c')
            ->where('c.id = :id')
            ->setParameter('id', $id)
        ;
        // On récupère la Query à partir du QueryBuilder
        $query = $queryBuilder->getQuery();

        // On récupère les résultats à partir de la Query
        $results =  $query->getResult();
//var_dump($results);
       // exit;
        // On retourne ces résultats
        return $results;

    }
}
