<?php

namespace BW\UsersBundle\Repository;

/**
 * CustomersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomersRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserCustomerById($id){
        $queryBuilder = $this
            ->createQueryBuilder('c')
            ->leftJoin('c.users', 'u')
            ->where('u.id = :id')
            ->setParameter('id', $id)
        ;
        // On récupère la Query à partir du QueryBuilder
        $query = $queryBuilder->getQuery();

        // On récupère les résultats à partir de la Query
        $results =  $query->getResult();
//var_dump($results);
   //     exit;
        // On retourne ces résultats
        return $results[0];
    }
}
